// 12 Official Societies matching stage-final-layout.png
export const SOCIETY_THEMES = {
  // RIGHT SIDE
  'Traditional Hilot Society': {
    name: 'Traditional Hilot Society',
    code: 'TH',
    row: 'TH',
    side: 'Right',
    colorName: 'Brown',
    pageBg: 'bg-[#fcf9f5]',
    headerBg: 'bg-[#fcf9f5]/95',
    cardBg: 'bg-[#f7efe6]',
    textDark: 'text-[#78350f]',
    subtext: 'text-[#92400e]',
    accentColor: '#854d0e',
    border: 'border-[#d6c7b2]',
    borderLight: 'border-[#ede4d8]',
    badge: {
      bg: '#fef3c7',
      text: '#78350f',
      border: '#d6c7b2',
    },
    tabActive: 'bg-[#f7efe6] text-[#78350f] border-2 border-[#854d0e] shadow-sm font-extrabold ring-1 ring-[#854d0e]/30',
    tabInactive: 'bg-white/85 text-[#78350f] hover:bg-[#fcf9f5] border border-[#d6c7b2] font-semibold',
    rowBadgeActive: 'bg-[#d6c7b2] text-[#78350f] font-extrabold',
    rowBadgeInactive: 'bg-[#f7efe6] text-[#92400e] font-semibold',
    tableBg: 'bg-[#f7efe6]',
    tableBorder: 'border-[#854d0e]',
    tableText: 'text-[#78350f]',
    buttonPrimary: 'bg-[#854d0e] hover:bg-[#713f12] text-white',
  },
  'Public Health Nursing Society': {
    name: 'Public Health Nursing Society',
    code: 'PH',
    row: 'PH',
    side: 'Right',
    colorName: 'Yellow',
    pageBg: 'bg-[#fefdf5]',
    headerBg: 'bg-[#fefdf5]/95',
    cardBg: 'bg-[#fef9c3]',
    textDark: 'text-[#713f12]',
    subtext: 'text-[#854d0e]',
    accentColor: '#ca8a04',
    border: 'border-[#fef08a]',
    borderLight: 'border-[#fefce8]',
    badge: {
      bg: '#fef9c3',
      text: '#854d0e',
      border: '#fde047',
    },
    tabActive: 'bg-[#fef9c3] text-[#713f12] border-2 border-[#ca8a04] shadow-sm font-extrabold ring-1 ring-[#ca8a04]/30',
    tabInactive: 'bg-white/85 text-[#854d0e] hover:bg-[#fefdf5] border border-[#fef08a] font-semibold',
    rowBadgeActive: 'bg-[#fde047] text-[#713f12] font-extrabold',
    rowBadgeInactive: 'bg-[#fef9c3] text-[#854d0e] font-semibold',
    tableBg: 'bg-[#fef9c3]',
    tableBorder: 'border-[#ca8a04]',
    tableText: 'text-[#713f12]',
    buttonPrimary: 'bg-[#eab308] hover:bg-[#ca8a04] text-[#0a1a33]',
  },
  'Nursing Informatics Society': {
    name: 'Nursing Informatics Society',
    code: 'I',
    row: 'I',
    side: 'Right',
    colorName: 'Baby Blue',
    pageBg: 'bg-[#f0f9ff]',
    headerBg: 'bg-[#f0f9ff]/95',
    cardBg: 'bg-[#e0f2fe]',
    textDark: 'text-[#0369a1]',
    subtext: 'text-[#0284c7]',
    accentColor: '#0284c7',
    border: 'border-[#bae6fd]',
    borderLight: 'border-[#e0f2fe]',
    badge: {
      bg: '#e0f2fe',
      text: '#0369a1',
      border: '#7dd3fc',
    },
    tabActive: 'bg-[#e0f2fe] text-[#0369a1] border-2 border-[#0284c7] shadow-sm font-extrabold ring-1 ring-[#0284c7]/30',
    tabInactive: 'bg-white/85 text-[#0369a1] hover:bg-[#f0f9ff] border border-[#bae6fd] font-semibold',
    rowBadgeActive: 'bg-[#bae6fd] text-[#0369a1] font-extrabold',
    rowBadgeInactive: 'bg-[#f0f9ff] text-[#0284c7] font-semibold',
    tableBg: 'bg-[#e0f2fe]',
    tableBorder: 'border-[#38bdf8]',
    tableText: 'text-[#0369a1]',
    buttonPrimary: 'bg-[#38bdf8] hover:bg-[#0284c7] text-[#0a1a33]',
  },
  'Nurses Against Hypertension Society': {
    name: 'Nurses Against Hypertension Society',
    code: 'H',
    row: 'H',
    side: 'Right',
    colorName: 'Maroon',
    pageBg: 'bg-[#fdf2f4]',
    headerBg: 'bg-[#fdf2f4]/95',
    cardBg: 'bg-[#fce7eb]',
    textDark: 'text-[#881337]',
    subtext: 'text-[#9f1239]',
    accentColor: '#881337',
    border: 'border-[#fbcfe8]',
    borderLight: 'border-[#ffe4e6]',
    badge: {
      bg: '#ffe4e6',
      text: '#881337',
      border: '#fda4af',
    },
    tabActive: 'bg-[#fce7eb] text-[#881337] border-2 border-[#881337] shadow-sm font-extrabold ring-1 ring-[#881337]/30',
    tabInactive: 'bg-white/85 text-[#881337] hover:bg-[#fdf2f4] border border-[#fbcfe8] font-semibold',
    rowBadgeActive: 'bg-[#fda4af] text-[#881337] font-extrabold',
    rowBadgeInactive: 'bg-[#ffe4e6] text-[#9f1239] font-semibold',
    tableBg: 'bg-[#fce7eb]',
    tableBorder: 'border-[#881337]',
    tableText: 'text-[#881337]',
    buttonPrimary: 'bg-[#881337] hover:bg-[#700f2b] text-white',
  },
  'Oncology Nursing Society': {
    name: 'Oncology Nursing Society',
    code: 'O',
    row: 'O',
    side: 'Right',
    colorName: 'Lavender',
    pageBg: 'bg-[#faf5ff]',
    headerBg: 'bg-[#faf5ff]/95',
    cardBg: 'bg-[#f3e8ff]',
    textDark: 'text-[#581c87]',
    subtext: 'text-[#6b21a8]',
    accentColor: '#9333ea',
    border: 'border-[#e9d5ff]',
    borderLight: 'border-[#f3e8ff]',
    badge: {
      bg: '#f3e8ff',
      text: '#581c87',
      border: '#d8b4fe',
    },
    tabActive: 'bg-[#f3e8ff] text-[#581c87] border-2 border-[#9333ea] shadow-sm font-extrabold ring-1 ring-[#9333ea]/30',
    tabInactive: 'bg-white/85 text-[#581c87] hover:bg-[#faf5ff] border border-[#e9d5ff] font-semibold',
    rowBadgeActive: 'bg-[#d8b4fe] text-[#581c87] font-extrabold',
    rowBadgeInactive: 'bg-[#f3e8ff] text-[#6b21a8] font-semibold',
    tableBg: 'bg-[#f3e8ff]',
    tableBorder: 'border-[#a855f7]',
    tableText: 'text-[#581c87]',
    buttonPrimary: 'bg-[#a855f7] hover:bg-[#9333ea] text-white',
  },
  'Renal Nursing Society': {
    name: 'Renal Nursing Society',
    code: 'R',
    row: 'R',
    side: 'Right',
    colorName: 'Orange',
    pageBg: 'bg-[#fff7ed]',
    headerBg: 'bg-[#fff7ed]/95',
    cardBg: 'bg-[#ffedd5]',
    textDark: 'text-[#7c2d12]',
    subtext: 'text-[#9a3412]',
    accentColor: '#ea580c',
    border: 'border-[#fed7aa]',
    borderLight: 'border-[#ffedd5]',
    badge: {
      bg: '#ffedd5',
      text: '#7c2d12',
      border: '#fdba74',
    },
    tabActive: 'bg-[#ffedd5] text-[#7c2d12] border-2 border-[#ea580c] shadow-sm font-extrabold ring-1 ring-[#ea580c]/30',
    tabInactive: 'bg-white/85 text-[#7c2d12] hover:bg-[#fff7ed] border border-[#fed7aa] font-semibold',
    rowBadgeActive: 'bg-[#fdba74] text-[#7c2d12] font-extrabold',
    rowBadgeInactive: 'bg-[#ffedd5] text-[#9a3412] font-semibold',
    tableBg: 'bg-[#ffedd5]',
    tableBorder: 'border-[#f97316]',
    tableText: 'text-[#7c2d12]',
    buttonPrimary: 'bg-[#f97316] hover:bg-[#ea580c] text-white',
  },

  // LEFT SIDE
  'Mental Health Society': {
    name: 'Mental Health Society',
    code: 'MH',
    row: 'MH',
    side: 'Left',
    colorName: 'Green',
    pageBg: 'bg-[#f0fdf4]',
    headerBg: 'bg-[#f0fdf4]/95',
    cardBg: 'bg-[#dcfce7]',
    textDark: 'text-[#14532d]',
    subtext: 'text-[#166534]',
    accentColor: '#16a34a',
    border: 'border-[#bbf7d0]',
    borderLight: 'border-[#dcfce7]',
    badge: {
      bg: '#dcfce7',
      text: '#14532d',
      border: '#86efac',
    },
    tabActive: 'bg-[#dcfce7] text-[#14532d] border-2 border-[#16a34a] shadow-sm font-extrabold ring-1 ring-[#16a34a]/30',
    tabInactive: 'bg-white/85 text-[#14532d] hover:bg-[#f0fdf4] border border-[#bbf7d0] font-semibold',
    rowBadgeActive: 'bg-[#86efac] text-[#14532d] font-extrabold',
    rowBadgeInactive: 'bg-[#dcfce7] text-[#166534] font-semibold',
    tableBg: 'bg-[#dcfce7]',
    tableBorder: 'border-[#16a34a]',
    tableText: 'text-[#14532d]',
    buttonPrimary: 'bg-[#16a34a] hover:bg-[#15803d] text-white',
  },
  'Maternal and Child Society': {
    name: 'Maternal and Child Society',
    code: 'MC',
    row: 'MC',
    side: 'Left',
    colorName: 'Pink',
    pageBg: 'bg-[#fdf2f8]',
    headerBg: 'bg-[#fdf2f8]/95',
    cardBg: 'bg-[#fce7f3]',
    textDark: 'text-[#831843]',
    subtext: 'text-[#9d174d]',
    accentColor: '#db2777',
    border: 'border-[#fbcfe8]',
    borderLight: 'border-[#fce7f3]',
    badge: {
      bg: '#fce7f3',
      text: '#831843',
      border: '#f472b6',
    },
    tabActive: 'bg-[#fce7f3] text-[#831843] border-2 border-[#db2777] shadow-sm font-extrabold ring-1 ring-[#db2777]/30',
    tabInactive: 'bg-white/85 text-[#831843] hover:bg-[#fdf2f8] border border-[#fbcfe8] font-semibold',
    rowBadgeActive: 'bg-[#f472b6] text-[#831843] font-extrabold',
    rowBadgeInactive: 'bg-[#fce7f3] text-[#9d174d] font-semibold',
    tableBg: 'bg-[#fce7f3]',
    tableBorder: 'border-[#ec4899]',
    tableText: 'text-[#831843]',
    buttonPrimary: 'bg-[#ec4899] hover:bg-[#db2777] text-white',
  },
  'Healthy Lung Society': {
    name: 'Healthy Lung Society',
    code: 'HL',
    row: 'HL',
    side: 'Left',
    colorName: 'Emerald Green',
    pageBg: 'bg-[#ecfdf5]',
    headerBg: 'bg-[#ecfdf5]/95',
    cardBg: 'bg-[#d1fae5]',
    textDark: 'text-[#064e3b]',
    subtext: 'text-[#065f46]',
    accentColor: '#059669',
    border: 'border-[#a7f3d0]',
    borderLight: 'border-[#d1fae5]',
    badge: {
      bg: '#d1fae5',
      text: '#064e3b',
      border: '#6ee7b7',
    },
    tabActive: 'bg-[#d1fae5] text-[#064e3b] border-2 border-[#059669] shadow-sm font-extrabold ring-1 ring-[#059669]/30',
    tabInactive: 'bg-white/85 text-[#064e3b] hover:bg-[#ecfdf5] border border-[#a7f3d0] font-semibold',
    rowBadgeActive: 'bg-[#6ee7b7] text-[#064e3b] font-extrabold',
    rowBadgeInactive: 'bg-[#d1fae5] text-[#065f46] font-semibold',
    tableBg: 'bg-[#d1fae5]',
    tableBorder: 'border-[#10b981]',
    tableText: 'text-[#064e3b]',
    buttonPrimary: 'bg-[#059669] hover:bg-[#047857] text-white',
  },
  'Gerontology Society': {
    name: 'Gerontology Society',
    code: 'G',
    row: 'G',
    side: 'Left',
    colorName: 'Gold',
    pageBg: 'bg-[#fffbeb]',
    headerBg: 'bg-[#fffbeb]/95',
    cardBg: 'bg-[#fef3c7]',
    textDark: 'text-[#78350f]',
    subtext: 'text-[#92400e]',
    accentColor: '#d97706',
    border: 'border-[#fde68a]',
    borderLight: 'border-[#fef3c7]',
    badge: {
      bg: '#fef3c7',
      text: '#78350f',
      border: '#fcd34d',
    },
    tabActive: 'bg-[#fef3c7] text-[#78350f] border-2 border-[#d97706] shadow-sm font-extrabold ring-1 ring-[#d97706]/30',
    tabInactive: 'bg-white/85 text-[#78350f] hover:bg-[#fffbeb] border border-[#fde68a] font-semibold',
    rowBadgeActive: 'bg-[#fcd34d] text-[#78350f] font-extrabold',
    rowBadgeInactive: 'bg-[#fef3c7] text-[#92400e] font-semibold',
    tableBg: 'bg-[#fef3c7]',
    tableBorder: 'border-[#e7c15a]',
    tableText: 'text-[#78350f]',
    buttonPrimary: 'bg-[#e7c15a] hover:bg-[#d97706] text-[#0a1a33]',
  },
  'Disaster Nursing Society': {
    name: 'Disaster Nursing Society',
    code: 'DN',
    row: 'DN',
    side: 'Left',
    colorName: 'Red',
    pageBg: 'bg-[#fef2f2]',
    headerBg: 'bg-[#fef2f2]/95',
    cardBg: 'bg-[#fee2e2]',
    textDark: 'text-[#7f1d1d]',
    subtext: 'text-[#991b1b]',
    accentColor: '#dc2626',
    border: 'border-[#fecaca]',
    borderLight: 'border-[#fee2e2]',
    badge: {
      bg: '#fee2e2',
      text: '#7f1d1d',
      border: '#fca5a5',
    },
    tabActive: 'bg-[#fee2e2] text-[#7f1d1d] border-2 border-[#dc2626] shadow-sm font-extrabold ring-1 ring-[#dc2626]/30',
    tabInactive: 'bg-white/85 text-[#7f1d1d] hover:bg-[#fef2f2] border border-[#fecaca] font-semibold',
    rowBadgeActive: 'bg-[#fca5a5] text-[#7f1d1d] font-extrabold',
    rowBadgeInactive: 'bg-[#fee2e2] text-[#991b1b] font-semibold',
    tableBg: 'bg-[#fee2e2]',
    tableBorder: 'border-[#ef4444]',
    tableText: 'text-[#7f1d1d]',
    buttonPrimary: 'bg-[#ef4444] hover:bg-[#dc2626] text-white',
  },
  'Diabetology Society': {
    name: 'Diabetology Society',
    code: 'D',
    row: 'D',
    side: 'Left',
    colorName: 'Blue',
    pageBg: 'bg-[#eff6ff]',
    headerBg: 'bg-[#eff6ff]/95',
    cardBg: 'bg-[#dbeafe]',
    textDark: 'text-[#1e3a8a]',
    subtext: 'text-[#1d4ed8]',
    accentColor: '#2563eb',
    border: 'border-[#bfdbfe]',
    borderLight: 'border-[#dbeafe]',
    badge: {
      bg: '#dbeafe',
      text: '#1e3a8a',
      border: '#93c5fd',
    },
    tabActive: 'bg-[#dbeafe] text-[#1e3a8a] border-2 border-[#2563eb] shadow-sm font-extrabold ring-1 ring-[#2563eb]/30',
    tabInactive: 'bg-white/85 text-[#1e3a8a] hover:bg-[#eff6ff] border border-[#bfdbfe] font-semibold',
    rowBadgeActive: 'bg-[#93c5fd] text-[#1e3a8a] font-extrabold',
    rowBadgeInactive: 'bg-[#dbeafe] text-[#1d4ed8] font-semibold',
    tableBg: 'bg-[#dbeafe]',
    tableBorder: 'border-[#3b82f6]',
    tableText: 'text-[#1e3a8a]',
    buttonPrimary: 'bg-[#3b82f6] hover:bg-[#2563eb] text-white',
  },
};

// Aliases mapping for codes, old names, and partial strings
const SOCIETY_ALIASES = {
  // RIGHT SIDE
  'TH': 'Traditional Hilot Society',
  'HILOT': 'Traditional Hilot Society',
  'TRADITIONAL HILOT': 'Traditional Hilot Society',
  'TRADITIONAL HILOT SOCIETY': 'Traditional Hilot Society',

  'PH': 'Public Health Nursing Society',
  'PUBLIC HEALTH': 'Public Health Nursing Society',
  'PUBLIC HEALTH NURSING SOCIETY': 'Public Health Nursing Society',

  'I': 'Nursing Informatics Society',
  'INFORMATICS': 'Nursing Informatics Society',
  'NURSING INFORMATICS': 'Nursing Informatics Society',
  'NURSING INFORMATICS SOCIETY': 'Nursing Informatics Society',

  'H': 'Nurses Against Hypertension Society',
  'HYPERTENSION': 'Nurses Against Hypertension Society',
  'NURSES AGAINST HYPERTENSION': 'Nurses Against Hypertension Society',
  'NURSES AGAINST HYPERTENSION SOCIETY': 'Nurses Against Hypertension Society',
  "NURSES' AGAINST HYPERTENSION SOCIETY": "Nurses Against Hypertension Society",

  'O': 'Oncology Nursing Society',
  'ONCOLOGY': 'Oncology Nursing Society',
  'ONCOLOGY NURSING SOCIETY': 'Oncology Nursing Society',

  'R': 'Renal Nursing Society',
  'RENAL': 'Renal Nursing Society',
  'RENAL NURSING SOCIETY': 'Renal Nursing Society',

  // LEFT SIDE
  'MH': 'Mental Health Society',
  'MENTAL HEALTH': 'Mental Health Society',
  'MENTAL HEALTH SOCIETY': 'Mental Health Society',
  'MENTAL HEALTH NURSING SOCIETY': 'Mental Health Society',

  'MC': 'Maternal and Child Society',
  'MATERNAL': 'Maternal and Child Society',
  'MATERNAL AND CHILD': 'Maternal and Child Society',
  'MATERNAL AND CHILD SOCIETY': 'Maternal and Child Society',
  'MATERNAL AND CHILD NURSING SOCIETY': 'Maternal and Child Society',

  'HL': 'Healthy Lung Society',
  'HEALTHY LUNG': 'Healthy Lung Society',
  'HEALTHY LUNG SOCIETY': 'Healthy Lung Society',
  'HEALTHY LUNG NURSING SOCIETY': 'Healthy Lung Society',

  'G': 'Gerontology Society',
  'GERONTOLOGY': 'Gerontology Society',
  'GERONTOLOGY SOCIETY': 'Gerontology Society',
  'GERONTOLOGY NURSING SOCIETY': 'Gerontology Society',

  'DN': 'Disaster Nursing Society',
  'DISASTER': 'Disaster Nursing Society',
  'DISASTER NURSING': 'Disaster Nursing Society',
  'DISASTER NURSING SOCIETY': 'Disaster Nursing Society',

  'D': 'Diabetology Society',
  'DIABETOLOGY': 'Diabetology Society',
  'DIABETOLOGY SOCIETY': 'Diabetology Society',
  'DIABETOLOGY NURSING SOCIETY': 'Diabetology Society',

  // Legacy mappings
  'SOCIETY A': 'Traditional Hilot Society',
  'SOCIETY B': 'Nursing Informatics Society',
  'SOCIETY C': 'Oncology Nursing Society',
  'SOCIETY D': 'Diabetology Society',
  'SOCIETY E': 'Maternal and Child Society',
  'SOCIETY F': 'Mental Health Society',
  'SOCIETY G': 'Gerontology Society',
};

export function normalizeSocietyName(soc) {
  if (!soc) return 'Nursing Informatics Society';
  const clean = String(soc).trim();
  const upper = clean.toUpperCase();
  if (SOCIETY_ALIASES[upper]) return SOCIETY_ALIASES[upper];
  if (SOCIETY_THEMES[clean]) return clean;

  // Search partial match
  for (const [key, val] of Object.entries(SOCIETY_ALIASES)) {
    if (upper.includes(key) || key.includes(upper)) {
      return val;
    }
  }

  return 'Nursing Informatics Society';
}

export function societyToSlug(soc) {
  const norm = normalizeSocietyName(soc);
  const theme = SOCIETY_THEMES[norm];
  return theme ? theme.code : norm.replace(/s+/g, '');
}

export function getSocietyTheme(societyName) {
  const normalized = normalizeSocietyName(societyName);
  return SOCIETY_THEMES[normalized] || SOCIETY_THEMES['Nursing Informatics Society'];
}
